<?php

/**
 * Implementation of hook_flush_caches().
 */
function trip_migrate_flush_caches() {
  trip_migrate_register_migrations();
}

/**
 * Register all D6->D7 migrations.
 */
function trip_migrate_register_migrations() {

  $common_arguments = array(
    'source_connection' => 'trip',
    'source_version' => 6,
  );


  // Users
  
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from Drupal 6'),
    'machine_name' => 'TripUser',
  );

  Migration::registerMigration('TripUserMigration', $arguments['machine_name'],
  $arguments);


  // Vocabularies
  
 $vocabulary_arguments = array(
  array(
    'description' => t('Migration of Destination terms from Drupal 6'),
    'machine_name' => 'TripTermDestination',
    'source_vocabulary' => '6',
    'destination_vocabulary' => 'tags',
    ),
  );

  $common_vocabulary_arguments = $common_arguments + array(
    'class_name' => 'DrupalTerm6Migration',
    'soft_dependencies' => array('TripUser'),
  );
                             
  foreach ($vocabulary_arguments as $arguments) {
    $arguments += $common_vocabulary_arguments;
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'], $arguments);
  }


  // Nodes
  
    $node_arguments = array(
      array(
        'description' => t('Migration of trip_forum nodes from Drupal 6'),
        'machine_name' => 'TripNodeForum',
        'source_type' => 'trip_forum',
        'destination_type' => 'article',      
      ),
      array(
        'description' => t('Migration of trip_forum_other nodes from Drupal 6'),
        'machine_name' => 'TripNodeForumOther',
        'source_type' => 'trip_forum_other',
        'destination_type' => 'article',
      ),
      array(
        'description' => t('Migration of trip_forum_expat nodes from Drupal 6'),
        'machine_name' => 'TripNodeForumExpat',
        'source_type' => 'trip_forum_expat',
        'destination_type' => 'article',
      ),
    );
  
    $common_node_arguments = $common_arguments + array(
      'user_migration' => 'TripUser',
      'class_name' => 'TripNodeMigration',
      'soft_dependencies' => array('TripTermDestination'),
  );
  
    foreach ($node_arguments as $arguments) {
      $arguments = array_merge_recursive($arguments, $common_node_arguments);
      Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
      $arguments);
    }
    

  // Comments
  
  $comment_arguments = array(
    array(
      'description' => t('Migration of trip_forum comments from Drupal 6'),
      'machine_name' => 'TripNodeForumComment',
      'source_type' => 'trip_forum',
      'destination_type' => 'article',
      'node_migration' => 'TripNodeForum',
    ),
    array(
      'description' => t('Migration of trip_forum_other comments from Drupal 6'),
      'machine_name' => 'TripNodeForumOtherComment',
      'source_type' => 'trip_forum_other',
      'destination_type' => 'article',
      'node_migration' => 'TripNodeForumOther',
    ),
    array(
      'description' => t('Migration of trip_forum_expat comments from Drupal 6'),
      'machine_name' => 'TripNodeForumExpatComment',
      'source_type' => 'trip_forum_expat',
      'destination_type' => 'article',
      'node_migration' => 'TripNodeForumExpat',
    )
  );

  $common_comment_arguments = $common_arguments + array(
    'user_migration' => 'TripUser',
    'class_name' => 'TripCommentMigration',
  );
    
  foreach ($comment_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_comment_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'], $arguments);
  }

}  
       

  
/**
 * Implementation of hook_migrate_api().
 */
function trip_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}
